fail_fast: true
repos:
    - repo: https://github.com/tillig/json-sort-cli
      rev: v3.0.3 # Use a version tag or SHA commit hash
      hooks:
          - id: json-sort
            args:
                - --autofix
    - repo: https://github.com/pappasam/toml-sort.git
      rev: v0.24.4
      hooks:
          - id: toml-sort-fix

    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.17.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/adamchainz/djade-pre-commit
      rev: "1.9.0" # Replace with the latest tag on GitHub
      hooks:
          - id: djade
            args: [--target-version, "4.2"] # Replace with Django version
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.4.0
      hooks:
          - id: autoflake
            args: [--remove-all-unused-imports, --in-place]
    - repo: https://github.com/pycqa/bandit
      rev: 1.9.4
      hooks:
          - id: bandit
            args: ["-iii", "-ll"]
    - repo: https://github.com/psf/black
      rev: 26.5.1
      hooks:
          - id: black
            language_version: python3.13
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-merge-conflict
          - id: detect-private-key
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: forbid-new-submodules
          - id: mixed-line-ending
          - id: trailing-whitespace
            language: python
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0 # Use the ref you want to point at
      hooks:
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.21.2
      hooks:
          - id: pyupgrade
            args: [--py312-plus]
    - repo: https://github.com/PyCQA/flake8
      rev: 7.3.0
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    "flake8-blind-except",
                    "flake8-docstrings",
                    "flake8-bugbear",
                    "flake8-comprehensions",
                    "flake8-docstrings",
                    "flake8-implicit-str-concat",
                    "pydocstyle>=5.0.0",
                ]
