[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["git-cliff>=2.12.0", "pre-commit>=4.5.1", "pylint>=4.0.4"]

[project]
name = "WeeknoteBot"
version = "1.10.0"
description = "A bot for generate WeekNote for Hugo"
authors = [{name = "Fundor333", email = "github@fundor333.com"}]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
  "click (>=8.1.8,<9.0.0)",
  "rich (>=13.9.4,<14.0.0)",
  "feedparser (>=6.0.11,<7.0.0)",
  "marshmallow (>=3.26.1,<4.0.0)",
  "requests (>=2.32.3,<3.0.0)"
]

[project.scripts]
weeknote = "weeknotebot.cli:cli"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.dotenv]
ignore = "false"
location = ".env.dev"

[tool.git-cliff.changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/docs/#introduction
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim_end }}\
    {% endfor %}
{% endfor %}
### Commit Statistics\n
- {{ statistics.commit_count }} commit(s) contributed to the release.
- {{ statistics.commits_timespan | default(value=0) }} day(s) passed between the first and last commit.
- {{ statistics.conventional_commit_count }} commit(s) parsed as conventional.
- {{ statistics.links | length }} linked issue(s) detected in commits.
{%- if statistics.links | length > 0 %}
	{%- for link in statistics.links %}
        {{ "  " }}- [{{ link.text }}]({{ link.href }}) (referenced {{ link.count }} time(s))
	{%- endfor %}
{%- endif %}
{%- if statistics.days_passed_since_last_release %}
	- {{ statistics.days_passed_since_last_release }} day(s) passed between releases.
{%- endif %}\n\n
"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[tool.git-cliff.git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
commit_parsers = [
  {message = "^feat", group = "<!-- 0 -->Features"},
  {message = "^fix", group = "<!-- 3 -->Bug Fixes"},
  {message = "^doc", group = "<!-- 1 -->Documentation"},
  {message = "^perf", group = "<!-- 2 -->Performance"},
  {message = "^refactor", group = "<!-- 5 -->Refactor"},
  {message = "^style", group = "<!-- 6 -->Styling"},
  {message = "^test", group = "<!-- 7 -->Testing"},
  {message = "^chore\\(release\\): prepare for", skip = true},
  {message = "^chore", group = "<!-- 8 -->Miscellaneous Tasks"},
  {body = ".*security", group = "<!-- 4 -->Security"},
  {body = ".*", group = "<!-- 9 -->Other (unconventional)"},
  {message = "^Merge '[^']+' into 'master'", skip = true}
] # An array of regex based parsers for extracting data from the commit message.filter_unconventional = false
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"

[tool.hatch.build.targets.sdist]
include = ["weeknotebot"]

[tool.hatch.build.targets.wheel]
include = ["weeknotebot"]

[tool.isort]
profile = "black"

[[tool.uv.index]]
name = "weeknotebot"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
